# 공휴일 설정
holidays:
  - date: "2025-01-01"
    name: "신정"
    type: "national"
  
  - date: "2025-02-01"
    name: "설날"
    type: "national"
  
  - date: "2025-02-02"
    name: "설날"
    type: "national"
  
  - date: "2025-02-03"
    name: "설날"
    type: "national"
  
  - date: "2025-03-01"
    name: "삼일절"
    type: "national"
  
  - date: "2025-05-05"
    name: "어린이날"
    type: "national"
  
  - date: "2025-05-08"
    name: "부처님오신날"
    type: "national"
  
  - date: "2025-06-06"
    name: "현충일"
    type: "national"
  
  - date: "2025-08-15"
    name: "광복절"
    type: "national"
  
  - date: "2025-09-28"
    name: "추석"
    type: "national"
  
  - date: "2025-09-29"
    name: "추석"
    type: "national"
  
  - date: "2025-09-30"
    name: "추석"
    type: "national"
  
  - date: "2025-10-03"
    name: "개천절"
    type: "national"
  
  - date: "2025-10-09"
    name: "한글날"
    type: "national"
  
  - date: "2025-12-25"
    name: "크리스마스"
    type: "national"
  
  # 회사 지정 휴일 (예시)
  - date: "2025-12-31"
    name: "연말 휴무"
    type: "company"
